[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/activate/*"
  to = "/activate.html"
  status = 200

[[redirects]]
  from = "/shop/*"
  to = "/shop.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
